wandb_version: 1

__cached__setup_devices:
  desc: null
  value: cuda:0
_n_gpu:
  desc: null
  value: 1
_name_or_path:
  desc: null
  value: t5-base
_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: huggingface
    huggingface_version: 4.9.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: train/global_step
      6:
      - 3
    - 1: train/loss
      5: 1
      6:
      - 1
    - 1: train/learning_rate
      5: 1
      6:
      - 1
    - 1: train/epoch
      5: 1
      6:
      - 1
    python_version: 3.7.0
    start_time: 1675413609
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      3:
      - 1
      - 7
      4: 3.7.0
      5: 0.12.1
      6: 4.9.2
      8:
      - 5
adafactor:
  desc: null
  value: true
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
add_cross_attention:
  desc: null
  value: false
architectures:
  desc: null
  value:
  - T5ForConditionalGeneration
bad_words_ids:
  desc: null
  value: null
bos_token_id:
  desc: null
  value: null
cfg:
  desc: null
  value: Salesforce/T5_base_prefix_text2cypher_with_cell_value.cfg
chunk_size_feed_forward:
  desc: null
  value: 0
d_ff:
  desc: null
  value: 3072
d_kv:
  desc: null
  value: 64
d_model:
  desc: null
  value: 768
dataloader_drop_last:
  desc: null
  value: false
dataloader_num_workers:
  desc: null
  value: 0
dataloader_pin_memory:
  desc: null
  value: true
ddp_find_unused_parameters:
  desc: null
  value: true
debug:
  desc: null
  value: '[]'
decoder_start_token_id:
  desc: null
  value: 0
deepspeed:
  desc: null
  value: None
disable_tqdm:
  desc: null
  value: false
diversity_penalty:
  desc: null
  value: 0.0
do_eval:
  desc: null
  value: true
do_predict:
  desc: null
  value: true
do_sample:
  desc: null
  value: false
do_train:
  desc: null
  value: true
dropout_rate:
  desc: null
  value: 0.1
early_stopping:
  desc: null
  value: false
encoder_no_repeat_ngram_size:
  desc: null
  value: 0
eos_token_id:
  desc: null
  value: 1
eval_accumulation_steps:
  desc: null
  value: None
eval_batch_size:
  desc: null
  value: 8
eval_steps:
  desc: null
  value: 5
evaluation_strategy:
  desc: null
  value: steps
feed_forward_proj:
  desc: null
  value: relu
finetuning_task:
  desc: null
  value: null
forced_bos_token_id:
  desc: null
  value: null
forced_eos_token_id:
  desc: null
  value: null
fp16:
  desc: null
  value: false
fp16_backend:
  desc: null
  value: auto
fp16_full_eval:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
generation_max_length:
  desc: null
  value: 512
generation_num_beams:
  desc: null
  value: 1
gradient_accumulation_steps:
  desc: null
  value: 8
gradient_checkpointing:
  desc: null
  value: false
greater_is_better:
  desc: null
  value: true
group_by_length:
  desc: null
  value: false
id2label:
  desc: null
  value:
    '0': LABEL_0
    '1': LABEL_1
ignore_data_skip:
  desc: null
  value: false
initializer_factor:
  desc: null
  value: 1.0
input_max_length:
  desc: null
  value: 512
is_decoder:
  desc: null
  value: false
is_encoder_decoder:
  desc: null
  value: true
label2id:
  desc: null
  value:
    LABEL_0: 0
    LABEL_1: 1
label_names:
  desc: null
  value: None
label_smoothing_factor:
  desc: null
  value: 0.0
layer_norm_epsilon:
  desc: null
  value: 1.0e-06
learning_rate:
  desc: null
  value: 0.0001
length_column_name:
  desc: null
  value: length
length_penalty:
  desc: null
  value: 1.0
load_best_model_at_end:
  desc: null
  value: true
load_weights_from:
  desc: null
  value: None
local_rank:
  desc: null
  value: 0
log_level:
  desc: null
  value: -1
log_level_replica:
  desc: null
  value: -1
log_on_each_node:
  desc: null
  value: true
logging_dir:
  desc: null
  value: output/T5_base_prefix_text2cypher_with_cell_value/runs/Feb03_16-40-08_DEP24073.uniwa.uwa.edu.au
logging_first_step:
  desc: null
  value: true
logging_steps:
  desc: null
  value: 4
logging_strategy:
  desc: null
  value: steps
lr_scheduler_type:
  desc: null
  value: linear
max_grad_norm:
  desc: null
  value: 1.0
max_length:
  desc: null
  value: 20
max_steps:
  desc: null
  value: -1
metric_for_best_model:
  desc: null
  value: avr
min_length:
  desc: null
  value: 0
model_type:
  desc: null
  value: t5
mp_parameters:
  desc: null
  value: ''
n_positions:
  desc: null
  value: 512
no_cuda:
  desc: null
  value: false
no_repeat_ngram_size:
  desc: null
  value: 0
num_beam_groups:
  desc: null
  value: 1
num_beams:
  desc: null
  value: 1
num_decoder_layers:
  desc: null
  value: 12
num_heads:
  desc: null
  value: 12
num_layers:
  desc: null
  value: 12
num_return_sequences:
  desc: null
  value: 1
num_train_epochs:
  desc: null
  value: 5.0
output_attentions:
  desc: null
  value: false
output_dir:
  desc: null
  value: output/T5_base_prefix_text2cypher_with_cell_value
output_hidden_states:
  desc: null
  value: false
output_past:
  desc: null
  value: true
output_scores:
  desc: null
  value: false
overwrite_output_dir:
  desc: null
  value: true
pad_token_id:
  desc: null
  value: 0
past_index:
  desc: null
  value: -1
per_device_eval_batch_size:
  desc: null
  value: 8
per_device_train_batch_size:
  desc: null
  value: 2
per_gpu_eval_batch_size:
  desc: null
  value: None
per_gpu_train_batch_size:
  desc: null
  value: None
predict_with_generate:
  desc: null
  value: true
prediction_loss_only:
  desc: null
  value: false
prefix:
  desc: null
  value: null
problem_type:
  desc: null
  value: null
pruned_heads:
  desc: null
  value: {}
push_to_hub:
  desc: null
  value: false
push_to_hub_model_id:
  desc: null
  value: T5_base_prefix_text2cypher_with_cell_value
push_to_hub_organization:
  desc: null
  value: None
push_to_hub_token:
  desc: null
  value: None
relative_attention_num_buckets:
  desc: null
  value: 32
remove_invalid_values:
  desc: null
  value: false
remove_unused_columns:
  desc: null
  value: true
repetition_penalty:
  desc: null
  value: 1.0
report_to:
  desc: null
  value: '[''tensorboard'', ''wandb'']'
resume_from_checkpoint:
  desc: null
  value: None
return_dict:
  desc: null
  value: true
return_dict_in_generate:
  desc: null
  value: false
run_name:
  desc: null
  value: T5_base_prefix_text2cypher_with_cell_value
save_on_each_node:
  desc: null
  value: false
save_steps:
  desc: null
  value: 5
save_strategy:
  desc: null
  value: steps
save_total_limit:
  desc: null
  value: 1
seed:
  desc: null
  value: 2
sep_token_id:
  desc: null
  value: null
sharded_ddp:
  desc: null
  value: '[]'
skip_memory_metrics:
  desc: null
  value: true
sortish_sampler:
  desc: null
  value: false
task_specific_params:
  desc: null
  value:
    summarization:
      early_stopping: true
      length_penalty: 2.0
      max_length: 200
      min_length: 30
      no_repeat_ngram_size: 3
      num_beams: 4
      prefix: 'summarize: '
    translation_en_to_de:
      early_stopping: true
      max_length: 300
      num_beams: 4
      prefix: 'translate English to German: '
    translation_en_to_fr:
      early_stopping: true
      max_length: 300
      num_beams: 4
      prefix: 'translate English to French: '
    translation_en_to_ro:
      early_stopping: true
      max_length: 300
      num_beams: 4
      prefix: 'translate English to Romanian: '
temperature:
  desc: null
  value: 1.0
tie_encoder_decoder:
  desc: null
  value: false
tie_word_embeddings:
  desc: null
  value: true
tokenizer_class:
  desc: null
  value: null
top_k:
  desc: null
  value: 50
top_p:
  desc: null
  value: 1.0
torch_dtype:
  desc: null
  value: null
torchscript:
  desc: null
  value: false
tpu_metrics_debug:
  desc: null
  value: false
tpu_num_cores:
  desc: null
  value: None
train_batch_size:
  desc: null
  value: 2
transformers_version:
  desc: null
  value: 4.9.2
use_bfloat16:
  desc: null
  value: false
use_cache:
  desc: null
  value: true
use_legacy_prediction_loop:
  desc: null
  value: false
vocab_size:
  desc: null
  value: 32102
warmup_ratio:
  desc: null
  value: 0.0
warmup_steps:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0.0
