wandb_version: 1

__cached__setup_devices:
  desc: null
  value: cuda:0
_n_gpu:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: huggingface
    huggingface_version: 4.9.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
    start_time: 1675397929
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      4: 3.7.0
      5: 0.12.1
      6: 4.9.2
      8:
      - 5
adafactor:
  desc: null
  value: true
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
cfg:
  desc: null
  value: Salesforce/T5_base_prefix_text2cypher_with_cell_value.cfg
dataloader_drop_last:
  desc: null
  value: false
dataloader_num_workers:
  desc: null
  value: 0
dataloader_pin_memory:
  desc: null
  value: true
ddp_find_unused_parameters:
  desc: null
  value: true
debug:
  desc: null
  value: []
deepspeed:
  desc: null
  value: null
disable_tqdm:
  desc: null
  value: false
do_eval:
  desc: null
  value: true
do_predict:
  desc: null
  value: true
do_train:
  desc: null
  value: true
eval_accumulation_steps:
  desc: null
  value: null
eval_steps:
  desc: null
  value: 5
evaluation_strategy:
  desc: null
  value: IntervalStrategy.STEPS
fp16:
  desc: null
  value: false
fp16_backend:
  desc: null
  value: auto
fp16_full_eval:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
generation_max_length:
  desc: null
  value: 512
generation_num_beams:
  desc: null
  value: 1
gradient_accumulation_steps:
  desc: null
  value: 8
greater_is_better:
  desc: null
  value: true
group_by_length:
  desc: null
  value: false
ignore_data_skip:
  desc: null
  value: false
input_max_length:
  desc: null
  value: 512
label_names:
  desc: null
  value: null
label_smoothing_factor:
  desc: null
  value: 0.0
learning_rate:
  desc: null
  value: 0.0001
length_column_name:
  desc: null
  value: length
load_best_model_at_end:
  desc: null
  value: true
load_weights_from:
  desc: null
  value: null
local_rank:
  desc: null
  value: 0
log_level:
  desc: null
  value: -1
log_level_replica:
  desc: null
  value: -1
log_on_each_node:
  desc: null
  value: true
logging_dir:
  desc: null
  value: output/T5_base_prefix_text2cypher_with_cell_value/runs/Feb03_12-18-48_DEP24073.uniwa.uwa.edu.au
logging_first_step:
  desc: null
  value: true
logging_steps:
  desc: null
  value: 4
logging_strategy:
  desc: null
  value: IntervalStrategy.STEPS
lr_scheduler_type:
  desc: null
  value: SchedulerType.LINEAR
max_grad_norm:
  desc: null
  value: 1.0
max_steps:
  desc: null
  value: -1
metric_for_best_model:
  desc: null
  value: avr
mp_parameters:
  desc: null
  value: ''
no_cuda:
  desc: null
  value: false
num_train_epochs:
  desc: null
  value: 5.0
output_dir:
  desc: null
  value: output/T5_base_prefix_text2cypher_with_cell_value
overwrite_output_dir:
  desc: null
  value: true
past_index:
  desc: null
  value: -1
per_device_eval_batch_size:
  desc: null
  value: 8
per_device_train_batch_size:
  desc: null
  value: 2
per_gpu_eval_batch_size:
  desc: null
  value: null
per_gpu_train_batch_size:
  desc: null
  value: null
predict_with_generate:
  desc: null
  value: true
prediction_loss_only:
  desc: null
  value: false
push_to_hub:
  desc: null
  value: false
push_to_hub_model_id:
  desc: null
  value: T5_base_prefix_text2cypher_with_cell_value
push_to_hub_organization:
  desc: null
  value: null
push_to_hub_token:
  desc: null
  value: null
remove_unused_columns:
  desc: null
  value: true
report_to:
  desc: null
  value:
  - tensorboard
  - wandb
resume_from_checkpoint:
  desc: null
  value: null
run_name:
  desc: null
  value: T5_base_prefix_text2cypher_with_cell_value
save_on_each_node:
  desc: null
  value: false
save_steps:
  desc: null
  value: 5
save_strategy:
  desc: null
  value: IntervalStrategy.STEPS
save_total_limit:
  desc: null
  value: 1
seed:
  desc: null
  value: 2
sharded_ddp:
  desc: null
  value: []
skip_memory_metrics:
  desc: null
  value: true
sortish_sampler:
  desc: null
  value: false
tpu_metrics_debug:
  desc: null
  value: false
tpu_num_cores:
  desc: null
  value: null
use_legacy_prediction_loop:
  desc: null
  value: false
warmup_ratio:
  desc: null
  value: 0.0
warmup_steps:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0.0
