wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: huggingface
    huggingface_version: 4.9.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
    start_time: 1675393337
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      4: 3.7.0
      5: 0.12.1
      6: 4.9.2
      8:
      - 5
